webserverPort: 8080

WebserverKey: "server.key"
WebserverCer: "server.cer"
WebserverHTTPS:
  enabled: false

logLevel: info

jsonExporter:
  enabled: true

prometheusExporter:
  enabled: true

influxDbExporter:
  enabled: false
  server: 1.2.3.4
  port: 8086
  org: <org>
  token: <token> or <username>:<password>
  database: <database(bucket)>
  measurement: <measurement>

mqtt:
  enabled: false
  brokerAddress: 1.2.3.4
  brokerPort: 1883
  username: username
  password: password
  clientId: weather-exporter
  topicPrefix: weather
